### ISSUE TITLE
Ethereum high cost?

### ISSUE THREAD

**Issue by PaulBernier** [explorecatena/catena-contract#2]
Great job on the explorer guys! 
I'm not sure I understand the choice of an Ethereum smart contract to store your data though. Why not using a pure data blockchain like Factom that is tailored to secure and store public data? Looking at a random [transaction](https://etherscan.io/tx/0x3ea1ae63c9009e9044dea8d8bdd380c0121967e6f738d0288e9b2861308e1bfe) I see you paid $0.27. With Factom you would have paid $0.001, and this price is _fixed_, it won't ever fluctuate depending on the market. That is order of magnitudes cheaper and you can predict the cost of storage. That sounds like 2 very compelling arguments that would help you scale smoothly your project to a much bigger data set.
So I'd be interested in hearing your thoughts!

**Comment by dylanseago** [comment]
Thanks for the suggestion! We'll take it into consideration.
