### ISSUE TITLE
Allow changing of "disclosureManagerAddress

### ISSUE THREAD

**Issue by moeadham** [explorecatena/catena-contract#3]
https://github.com/explorecatena/catena-contract/blob/ac189995bef9142e78bdee3642a5f0b0afbc927f/contracts/DisclosureAgreementTracker.sol#L65

@dylanseago I suggest that we have an onlyOwner function that allows a set & change of the disclosureManagerAddress in case we change it in the future.

Here is a good example:
https://etherscan.io/address/0xe5f867de1ea81346df5181b8b48dd6b0bb3357b0#code <- Line 236

**Comment by dylanseago** [comment]
This contract is meant as an "add-on" for an existing DisclosureManager and references disclosures in it by their row number. If the contract address were to change this contract should also be redeployed.

Another option would be to completely remove `disclosureManagerAddress` and `disclosureIndex` from `Agreement` which would allow this contract to still be used if DisclosureManager were rewritten in the future. The one drawback is that there will be nothing on the blockchain tying each disclosure to these agreements.

**Comment by moeadham** [comment]
Cool. Makes sense. Closing.
